[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "at-spi2-atk",
  "libdrm",
  "libxkbcommon",
  "libXcomposite",
  "libXdamage",
  "libXrandr",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo",
  "dbus",
  "expat",
  "cups",
  "xorg.libX11",
  "xorg.libxcb"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -c 'PUPPETEER_EXECUTABLE_PATH=$(which chromium) node dist/server.js'"